-- MySQL Script generated by MySQL Workbench
-- Sat Aug  4 10:56:13 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema petomatic_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema petomatic_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `petomatic_database` DEFAULT CHARACTER SET utf8 ;
USE `petomatic_database` ;

-- -----------------------------------------------------
-- Table `petomatic_database`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petomatic_database`.`users` ;

CREATE TABLE IF NOT EXISTS `petomatic_database`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `avatar` BLOB NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petomatic_database`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petomatic_database`.`customers` ;

CREATE TABLE IF NOT EXISTS `petomatic_database`.`customers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `phone_number` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petomatic_database`.`visits_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petomatic_database`.`visits_type` ;

CREATE TABLE IF NOT EXISTS `petomatic_database`.`visits_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petomatic_database`.`species`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petomatic_database`.`species` ;

CREATE TABLE IF NOT EXISTS `petomatic_database`.`species` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petomatic_database`.`genders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petomatic_database`.`genders` ;

CREATE TABLE IF NOT EXISTS `petomatic_database`.`genders` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petomatic_database`.`pets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petomatic_database`.`pets` ;

CREATE TABLE IF NOT EXISTS `petomatic_database`.`pets` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `age` VARCHAR(45) NULL,
  `start_date` VARCHAR(45) BINARY NULL,
  `customer_id` INT UNSIGNED NOT NULL,
  `species_id` INT UNSIGNED NOT NULL,
  `gender_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pets_customers1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_pets_species1_idx` (`species_id` ASC) VISIBLE,
  INDEX `fk_pets_gender1_idx` (`gender_id` ASC) VISIBLE,
  CONSTRAINT `fk_pets_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `petomatic_database`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pets_species1`
    FOREIGN KEY (`species_id`)
    REFERENCES `petomatic_database`.`species` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pets_gender1`
    FOREIGN KEY (`gender_id`)
    REFERENCES `petomatic_database`.`genders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petomatic_database`.`visits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petomatic_database`.`visits` ;

CREATE TABLE IF NOT EXISTS `petomatic_database`.`visits` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `short_description` VARCHAR(255) NULL,
  `date` DATETIME NULL,
  `files` VARCHAR(45) NULL,
  `visit_type_id` INT UNSIGNED NOT NULL,
  `pet_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_visits_visits_type1_idx` (`visit_type_id` ASC) VISIBLE,
  INDEX `fk_visits_pets1_idx` (`pet_id` ASC) VISIBLE,
  CONSTRAINT `fk_visits_visits_type1`
    FOREIGN KEY (`visit_type_id`)
    REFERENCES `petomatic_database`.`visits_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visits_pets1`
    FOREIGN KEY (`pet_id`)
    REFERENCES `petomatic_database`.`pets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
